# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sensors Unleashed Blog
tagline:          'Open Source wireless control'
description:      'Think, Invent, Present, Again!!'         
baseurl:          /blog
url:              https://www.sensorsunleashed.com
enforce_ssl:      www.sensorsunleashed.com

author:
  name:           'Ole Nissen'
  url:            https://twitter.com/olenissen

paginate:         5

# Pages
pages:
  Archive: '/archive'
  About: '/about'
  Tags: '/tags'

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/SensorsUnleashed

sass:
  sass_dir: _sass
  style: :compressed