# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sensors Unleashed Blog
tagline:          'Open Source wireless control'
description:      'A project developed using open standards, with open tools in an open community. Project started by <a href="https://www.linkedin.com/in/ole-nissen-36b38110?trk=hp-identity-name" target="_blank">Ole Nissen</a>.'         
baseurl:          /blog
url:              http://www.sensorsunleashed.com

author:
  name:           'Ole Nissen'
  url:            https://twitter.com/olenissen

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/SensorsUnleashed
